/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./*.html",
    "./js/**/*.js"
  ],
  theme: {
    extend: {
      colors: {
        tertiary: "#febb3b",
        "on-primary": "#00315f",
        background: "#101419",
        "accent-hover": "#4A8AE0",
        "ambient-glow": "rgba(91, 155, 240, 0.08)",
        "on-primary-fixed-variant": "#004786",
        "text-secondary": "#8A94A6",
        "surface-container-low": "#181c21",
        outline: "#8b919d",
        "inverse-primary": "#005fb0",
        "surface-base": "#090D12",
        "surface-container": "#1c2025",
        "on-tertiary": "#422c00",
        "surface-glass": "rgba(24, 28, 38, 0.65)",
        "outline-variant": "#414751",
        "on-primary-container": "#003261",
        "glass-border-subtle": "rgba(255, 255, 255, 0.06)",
        "secondary-container": "#12487e",
        "on-error": "#690005",
        "on-surface-variant": "#c1c6d3",
        "primary-fixed-dim": "#a6c8ff",
        "on-primary-fixed": "#001c3b",
        "surface-container-lowest": "#0a0e14",
        "on-secondary-fixed": "#001c39",
        primary: "#a6c8ff",
        "surface-glass-active": "rgba(32, 38, 52, 0.8)",
        "secondary-fixed": "#d4e3ff",
        "tertiary-container": "#ca8e00",
        "secondary-fixed-dim": "#a4c9ff",
        "surface-bright": "#36393f",
        "tertiary-fixed-dim": "#febb3b",
        "error-container": "#93000a",
        "surface-tint": "#a6c8ff",
        "on-secondary-container": "#8cb7f4",
        "glass-border": "rgba(255, 255, 255, 0.12)",
        "text-primary": "#F4F6FB",
        "surface-container-high": "#262a30",
        "on-surface": "#e0e2ea",
        surface: "#101419",
        "on-secondary": "#00315d",
        "surface-dim": "#101419",
        "surface-variant": "#31353b",
        "tertiary-fixed": "#ffdeab",
        "on-tertiary-fixed": "#281900",
        "on-background": "#e0e2ea",
        "primary-fixed": "#d5e3ff",
        "surface-container-highest": "#31353b",
        "on-tertiary-fixed-variant": "#5f4100",
        "text-muted": "#525C6E",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e0e2ea",
        error: "#ffb4ab",
        "on-tertiary-container": "#442d00",
        secondary: "#a4c9ff",
        "on-secondary-fixed-variant": "#12487e",
        "inverse-on-surface": "#2d3136",
        "primary-container": "#5b9bf0"
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      },
      spacing: {
        "space-sm": "0.5rem",
        "margin-tablet": "2rem",
        "space-md": "1rem",
        "space-xl": "2rem",
        margin: "1.25rem",
        "gutter-sm": "0.75rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        gutter: "1rem"
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "mono-timer": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "mono-timer": ["48px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }]
      }
    }
  },
  plugins: []
};
